repos:
- repo: local
  hooks:
  - id: update-readme-structure
    name: Update README Structure
    entry: bash -c 'python scripts/update_readme_structure.py && git add README.md'
    language: python
    pass_filenames: false
    always_run: true
    additional_dependencies: [python-dotenv, openai>=1.0.0]

- repo: https://github.com/psf/black
  rev: 23.10.1  # Use the latest stable version
  hooks:
  - id: black
    name: Format Python code with Black
    language_version: python3
    types: [python]
    args: ["--line-length=88"]  # Optional: specify line length

- repo: https://github.com/pycqa/flake8
  rev: 6.1.0  # Use the latest stable version
  hooks:
  - id: flake8
    name: Check Python code style with Flake8
    additional_dependencies: [flake8-docstrings]
    args: ["--max-line-length=88", "--extend-ignore=E203"]  # Make flake8 compatible with Black

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0  # Use the latest stable version
  hooks:
  - id: trailing-whitespace
    name: Trim trailing whitespace
  - id: end-of-file-fixer
    name: Ensure files end with a newline
  - id: check-yaml
    name: Check YAML syntax
  - id: check-json
    name: Check JSON syntax
  - id: check-toml
    name: Check TOML syntax
  - id: detect-private-key
    name: Check for committed private keys
