repos:
  - repo: local
    hooks:
      - id: update-readme-structure
        name: Update README Structure
        entry: bash -c 'python scripts/update_readme_structure.py && git add README.md'
        language: python
        pass_filenames: false
        always_run: true
        verbose: true
        additional_dependencies: [python-dotenv, openai>=1.0.0]

      - id: pytype-annotations
        name: Infer and validate types with Pytype
        entry: bash -c 'pytype $(git diff --cached --name-only --diff-filter=ACM "*.py" | xargs)'
        language: python
        types: [python]
        additional_dependencies: [pytype==2023.10.17]
        pass_filenames: false

      - id: typescript-strict-check
        name: TypeScript Type Check
        entry: npx tsc --noEmit --strict
        language: system
        types: [ts, tsx]
        pass_filenames: false

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        name: Format Python code with Black
        language_version: python3
        types: [python]
        args: ['--line-length=108']

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        name: Check Python code style with Flake8
        additional_dependencies: [flake8-docstrings]
        args: ['--max-line-length=108', '--extend-ignore=E203']

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        name: Format JavaScript/TypeScript with Prettier
        types_or: [javascript, jsx, ts, tsx, json, yaml, markdown]
        args: ['--print-width=100', '--single-quote']

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.39.0
    hooks:
      - id: eslint
        name: Lint JavaScript/TypeScript with ESLint
        files: \.(js|ts|tsx)$
        types: [file]
        additional_dependencies:
          - eslint@8.39.0
          - eslint-config-prettier@8.8.0
          - '@typescript-eslint/eslint-plugin@5.59.2'
          - '@typescript-eslint/parser@5.59.2'

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        name: Trim trailing whitespace
        stages: [pre-commit]
      - id: end-of-file-fixer
        name: Ensure files end with a newline
        stages: [pre-commit]
      - id: check-yaml
        name: Check YAML syntax
        stages: [pre-commit]
      - id: debug-statements
        name: Check for debug statements
        stages: [pre-commit]
      - id: check-added-large-files
        name: Check for added large files
        stages: [pre-commit]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.262
    hooks:
      - id: ruff
        name: Format Python code with Ruff
        args: [--fix, --exit-non-zero-on-fix, --line-length=108]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
      - id: mypy
        name: Type check with Mypy
        additional_dependencies: [types-requests, types-pytz]
