version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - ENVIRONMENT=production
    env_file: .env
    environment:
      - ENVIRONMENT=production
      - DEBUG=false
    ports:
      - "8000:8000"  # For web interface
    restart: unless-stopped
    command: python src/main.py 