name: Tag Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to tag (e.g. v1.2.3)'
        required: true

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create tag
        run: |
          git tag ${{ github.event.inputs.version }}
          git push origin ${{ github.event.inputs.version }}
